<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>answer</name>
   <tag></tag>
   <elementGuidId>f6cdf432-d7cf-4873-9c96-9d1053549ac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberAnswerField</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'numberAnswerField']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberAnswerField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#numberAnswerField</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e5e48c4-1711-4683-83a7-3e3f5979ddad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberAnswerField</value>
      <webElementGuid>a17e0a67-cfda-4c8c-bd3b-a1c0c1dc2b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberAnswer</value>
      <webElementGuid>04e2ac9c-efcf-4bce-9dc0-c1b1efa1775d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element text medium</value>
      <webElementGuid>46cbe096-5b5a-40ef-82ec-a91b93e24b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88cdc665-cabc-4d8d-bcc0-1322ae4f2e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>513962e5-2aeb-42bd-b60b-bdc771ea0bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberAnswerField&quot;)</value>
      <webElementGuid>a057d16d-f100-4555-aefa-5acaa70ebf98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberAnswerField']</value>
      <webElementGuid>3ea95e04-a08d-49ec-a658-5da57786eb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='answerForm']/div/div[2]/input</value>
      <webElementGuid>c470ad69-7f68-4def-8d87-d4d778f1957c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[4]/div/div[2]/input</value>
      <webElementGuid>50878ec6-6bc5-480e-b8d6-f53d4121624f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'numberAnswerField' and @name = 'numberAnswer' and @type = 'text']</value>
      <webElementGuid>f14db67c-c3e5-4ca9-933a-44195846e948</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
