<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Build</name>
   <tag></tag>
   <elementGuidId>204178d1-9571-4991-986c-fe8343b25807</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectBuild</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'selectBuild']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectBuild']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#selectBuild</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d049d94a-57f4-4a38-826b-94c8175130f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element select medium</value>
      <webElementGuid>d4d653f8-3821-4f30-9982-518524c813a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectBuild</value>
      <webElementGuid>a8ad790b-7a2c-4cc2-a8bc-647f4739bcd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectBuild</value>
      <webElementGuid>235554c5-e8da-4c0a-b5a4-7599438676d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>buildChanged(this.preset)</value>
      <webElementGuid>8d0f0152-8458-4ff5-aac5-cfe58632a851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                          Prototype
                          1
                          2
                          3
                          4
                          5
                          6
                          7
                          8
                          9
                      </value>
      <webElementGuid>8b1d00a9-d8c9-4d77-b4c0-8a47a36642e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectBuild&quot;)</value>
      <webElementGuid>c4ef68e7-cf88-4a58-aa98-3f10aeb7e4c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectBuild']</value>
      <webElementGuid>34b6c5cc-6e7e-43c9-8b81-81cf23641980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-body']/div/div/div/div/div[2]/select</value>
      <webElementGuid>b4b3a5f7-15ab-4d21-befa-c115846f7cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build'])[1]/following::select[1]</value>
      <webElementGuid>f726e0f9-8108-444c-a2b7-aa1a769c2cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prototype'])[1]/following::select[1]</value>
      <webElementGuid>a822a599-bd9d-4718-b47c-024a96e5be82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[1]/preceding::select[1]</value>
      <webElementGuid>3ee89a69-8efa-4c51-a770-3f4c07efb2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First number'])[1]/preceding::select[1]</value>
      <webElementGuid>37c8a6cf-465a-41ec-a0a3-440376409254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5f9d125b-2f64-4bd9-bc1a-5704fe7f54d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectBuild' and @name = 'selectBuild' and (text() = ' 
                          Prototype
                          1
                          2
                          3
                          4
                          5
                          6
                          7
                          8
                          9
                      ' or . = ' 
                          Prototype
                          1
                          2
                          3
                          4
                          5
                          6
                          7
                          8
                          9
                      ')]</value>
      <webElementGuid>790318e8-f417-49f0-aabb-c41b782f0783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
