<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>snum</name>
   <tag></tag>
   <elementGuidId>1a6f67e9-6d4a-4ca4-9910-8c8d9017211c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#number2Field</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'number2Field']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='number2Field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#number2Field</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e206e1d2-82bb-4b3c-a574-c243ce9f9f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number2Field</value>
      <webElementGuid>425f3a81-b7f6-49a7-9746-df5a787a6baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number2</value>
      <webElementGuid>b8937b06-ae8d-443a-9613-4ccd4e89bfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element text medium</value>
      <webElementGuid>86f695e1-bb7a-4b71-ae8b-5943226d8c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed71674c-f86a-4c08-89f7-0ca50c10a12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>66f562f3-c494-4466-85d1-4990722d7b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number2Field&quot;)</value>
      <webElementGuid>1d550c50-a29a-49e0-8b00-35a7c5866bdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='number2Field']</value>
      <webElementGuid>a73c0d02-58d0-4575-bb97-8bad0080c0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calcForm']/div[2]/div[2]/input</value>
      <webElementGuid>15a75ea8-d521-43b7-b464-fc15e936cbdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>7e6eb0eb-e2c6-4900-8379-c8579777dba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'number2Field' and @name = 'number2' and @type = 'text']</value>
      <webElementGuid>b35c0490-a129-4f18-94e8-0414ca96fa8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
